apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
    tier: frontend
  name: my-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: django6
    app.kubernetes.io/name: helm-oci-django-atp
  sessionAffinity: None
  type: LoadBalancer
